{{ if .Values.encryption.generate }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "pocketbase.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "pocketbase.annotations" . | indent 4 }}
    {{- toYaml .Values.ingress.annotations  | nindent 4 }}
  labels:
    {{- include "pocketbase.labels" . | indent 4 }}
type: opaque
data:
  encryption-key: {{- include "pocketbase.encryption.key" . | b64enc | quote }}
{{ end }}