# language=ansible
---
- name: "Setup DNS Proxy"
  hosts: "*"
  vars:
    internal_cidr: "{{ lookup('env', 'PREMISE_INTERNAL_CIDR') | default('172.16.0.1/24', True) }}"
    internal_ip: "{{ lookup('env', 'PREMISE_INTERNAL_IP') | default('172.16.0.1', True) }}"
    internal_dhcp_range: "{{ lookup('env', 'PREMISE_INTERNAL_DHCP_RANGE') | default('172.16.0.192,172.16.0.254', True) }}"
  tasks:
    -
      name: "Create folder structure"
      ansible.builtin.file:
        path: /srv/dnsmasq
        state: directory
    -
      name: "Add configuration files"
      ansible.builtin.template:
        dest: "/srv/dnsmasq/{{ item }}"
        src: "dnsmasq/{{ item }}.j2"
      with_items:
        - dnsmasq.conf
        - dhcp.conf
        - netboot.conf
    -
      name: "Run DNSMASQ container"
      containers.podman.podman_container:
        state: started
        recreate: true
        name: dnsmasq
        image: quay.io/poseidon/dnsmasq
        command: -d -k
        volume:
          - "/srv/dnsmasq:/etc/dnsmasq.d"
        cap_add:
          - NET_ADMIN
          - NET_RAW
        ports:
          - "{{ internal_ip }}:53:53/tcp"
          - "{{ internal_ip }}:53:53/udp"
          - "{{ internal_ip }}:67:67/tcp"
          - "{{ internal_ip }}:67:67/udp"
          - "{{ internal_ip }}:69:69/tcp"
          - "{{ internal_ip }}:69:69/udp"

