# language=ansible
---
- hosts: localhost
  connection: local
  vars_prompt:
    -
      prompt: "What is the hostname for your premise server that your SSH agent can connect to?"
      name: premise_hostname
      private: no
    -
      prompt: "What domain name this server should be known, and use for DHCP assignments? [ssh-hostname]"
      name: premise_domain_input
      private: no
    -
      prompt: "Which CIDR is used for your premise private network?"
      name: premise_internal_cidr
      default: "172.16.0.0/24"
      private: no
    -
      prompt: "What IP address your premise server uses for the private network?"
      name: premise_internal_ip
      default: "172.16.0.1"
      private: no
    -
      prompt: "What IP should be your DHCP start?"
      name: premise_internal_dhcp_begin
      default: "172.16.0.192"
      private: no
    -
      prompt: "What IP should be your DHCP end?"
      name: premise_internal_dhcp_end
      default: "172.16.0.254"
      private: no

  vars:
    premise_domain: "{{ premise_domain_input | default('premise_hostname') }}"

  tasks:
    - name: "Generating .env file"
      ansible.builtin.template:
        backup: yes
        src: dotenv.j2
        dest: ../.env
