# language=ansible
---
- name: "Setup Matchbox"
  hosts: "*"
  vars:
    mbpath: "/srv/matchbox"
    server_fqdn: "{{ lookup('env', 'PREMISE_SERVER_FQDN') | default('premise-manager.site.net', True) }}"
    internal_cidr: "{{ lookup('env', 'PREMISE_INTERNAL_CIDR') | default('172.16.0.1/24', True)  }}"
    internal_ip: "{{ lookup('env', 'PREMISE_INTERNAL_IP') | default('172.16.0.1', True)  }}"
    coreos_mirror: "https://builds.coreos.fedoraproject.org/prod/streams/stable/builds"
    coreos_version: "34.20211031.3.0"
    coreos_arch: "x86_64"
  tasks:
    - include_tasks: matchbox/tasks/00-folder-structure.yml
    - include_tasks: matchbox/tasks/01-generate-certificates.yml
    - include_tasks: matchbox/tasks/02-setup-profile.yml
    - include_tasks: matchbox/tasks/03-setup-ignition.yml
    - include_tasks: matchbox/tasks/04-cache-bootfiles.yml
    -
      name: "Run Matchbox container"
      containers.podman.podman_container:
        recreate: yes
        state: started
        name: matchbox
        image: quay.io/poseidon/matchbox
        command:
          - -address=0.0.0.0:8080
          - -rpc-address=0.0.0.0:8081
          - -log-level=debug
        volume:
          - "{{ mbpath }}/etc:/etc/matchbox:Z"
          - "{{ mbpath }}:/var/lib/matchbox:Z"
        ports:
          - "{{ internal_ip }}:8080:8080/tcp"
          - "{{ internal_ip }}:8081:8081/tcp"
