# language=ansible
---
-
  name: "Generate SSH Keypair"
  community.crypto.openssh_keypair:
    path: "{{ mbpath }}/keys/id_{{ server_fqdn | replace('.','-') }}_ed25519"
    type: ed25519
  register: keypair
-
  name: "Setup butane files"
  ansible.builtin.template:
    dest: "{{ mbpath }}/ignition/{{ item }}.bu"
    src: ../ignition/{{ item }}.bu.j2
  with_items:
    - fedora-coreos
-
  name: "Compile to ignition"
  containers.podman.podman_container:
    rm: yes
    interactive: yes
    name: "compile-{{ item }}"
    image: quay.io/coreos/butane:release
    command:
      - -o {{ item }}.ign
      - --strict {{ item }}.bu
    workdir: /ignition
    volumes:
      - "{{ mbpath }}/ignition:/ignition"
  with_items:
    - fedora-coreos
