import type {ResourceAllocationConfig, BitnamiImage, Output} from '@adaliszk/pulumi'

export interface PostgresOptions
{
    image?: BitnamiImage
    replicaCount?: number
    nodeSelector?: object
    resources?: ResourceAllocationConfig
    annotations?: object
    labels?: object
    metrics?: {
        enabled: boolean
        resources?: ResourceAllocationConfig
        annotations?: object
        labels?: object
    }
    persistence?: {
        enabled: boolean
        storageClass?: string
        size?: string
        annotations?: object
        labels?: object
    }
    networkPolicy?: {
        enabled: boolean
        allowExternal?: boolean
    }
}

export interface PostgresChartOptions extends PostgresOptions
{
    nameOverride?: string
    architecture?: 'standalone' | 'replication'
    replication?: {
        synchronousCommit?: 'on' | 'off' | 'remote_appy' | 'remote_write' | 'local'
        numSynchronousReplicas?: number
        applicationName?: string
    }
    auth?: {
        enablePostgresUser?: boolean
        postgresPassword?: string
        username?: string
        password?: string
        database?: string
        replicationUsername?: string
        replicationPassword?: string
        existingSecret?: Output<string>
    }
    tls?: {
        enabled?: boolean
        autoGenerated?: boolean
    }
}