# language=ansible
---
-
  name: "Setup interface"
  ansible.builtin.template:
    dest: /etc/network/interfaces.d/50-vpc.cfg
    src: vpc.cfg.j2
-
  name: "Restart Networking"
  ansible.builtin.systemd:
    state: restarted
    name: networking
